/**
 * Ícones Lucide usados no app + galeria de referência para a aba Configurações → ÍCONES.
 * Para ver todos os ícones disponíveis: https://lucide.dev/icons
 */

import type { LucideIcon } from 'lucide-react'
import {
  Home,
  Film,
  DollarSign,
  FileText,
  CreditCard,
  Users,
  BarChart3,
  Settings,
  ScrollText,
  ClipboardList,
  Image,
  Calendar,
  CalendarDays,
  Wallet,
  FolderOpen,
  User,
  Mail,
  Phone,
  MapPin,
  Building2,
  Camera,
  Clapperboard,
  LayoutGrid,
  ListOrdered,
  StickyNote,
  PenLine,
  FileCheck,
  Receipt,
  Banknote,
  PieChart,
  Target,
  Truck,
  UtensilsCrossed,
  Shirt,
  Paintbrush,
  Mic,
  Headphones,
  Wrench,
  Box,
  Car,
  Coffee,
  AlertCircle,
  CheckCircle,
  Clock,
  Info,
  ChevronRight,
  Search,
  Plus,
  Trash2,
  Edit,
  Copy,
  Save,
  LogOut,
  Menu,
  X,
  // Vídeo e multimídia
  Video,
  VideoOff,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Square,
  Tv,
  Monitor,
  MonitorPlay,
  // Escrita
  Pencil,
  Highlighter,
  Pen,
  FilePenLine,
  // Documentos
  File,
  FilePlus,
  FileMinus,
  Folder,
  FolderPlus,
  Archive,
  // Dinheiro e pagamentos
  CircleDollarSign,
  BadgeDollarSign,
  // Navegação, abrir/fechar, copiar/colar
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  PanelRightOpen,
  PanelLeftClose,
  DoorOpen,
  DoorClosed,
  ClipboardCopy,
  ClipboardPaste,
  Minus,
  // Contatos
  MessageCircle,
  MessageSquare,
  ContactRound,
  Send,
  // Fotografia e multimídia
  Images,
  ImagePlus,
  // Planilhas, cadernos, textos, folhas, anotações
  Notebook,
  NotebookText,
  NotebookTabs,
  Sheet,
  BookOpen,
  BookMarked,
  FileStack,
  FileType,
} from 'lucide-react'

/** Ícones atualmente usados no sistema (menu inferior, Filme, Header) */
export const APP_ICONS: { name: string; Icon: LucideIcon; usage: string }[] = [
  { name: 'Home', Icon: Home, usage: 'Menu inferior – HOME' },
  { name: 'Film', Icon: Film, usage: 'Menu inferior – FILME' },
  { name: 'DollarSign', Icon: DollarSign, usage: 'Menu inferior – ORÇAMENTO' },
  { name: 'FileText', Icon: FileText, usage: 'Menu inferior – ORÇ. FINAL' },
  { name: 'CreditCard', Icon: CreditCard, usage: 'Menu inferior – FECHAMENTO' },
  { name: 'Users', Icon: Users, usage: 'Menu inferior – EQUIPE' },
  { name: 'BarChart3', Icon: BarChart3, usage: 'Menu inferior – DASHBOARD' },
  { name: 'Settings', Icon: Settings, usage: 'Header – Configurações' },
  { name: 'ScrollText', Icon: ScrollText, usage: 'Página Filme – ROTEIRO' },
  { name: 'ClipboardList', Icon: ClipboardList, usage: 'Página Filme – DECUPAGEM' },
  { name: 'Image', Icon: Image, usage: 'Página Filme – STORYBOARD' },
  { name: 'CalendarDays', Icon: CalendarDays, usage: 'Página Filme – ORDEM DO DIA' },
  { name: 'Plus', Icon: Plus, usage: 'Header – Novo' },
  { name: 'FolderOpen', Icon: FolderOpen, usage: 'Header – Abrir' },
  { name: 'Copy', Icon: Copy, usage: 'Header – Salvar cópia' },
  { name: 'Save', Icon: Save, usage: 'Header – Salvar' },
  { name: 'LogOut', Icon: LogOut, usage: 'Header – Sair' },
]

/** Galeria de referência: ícones úteis para escolher em novas telas. Nome = como importar de lucide-react. */
export const GALLERY_ICONS: { name: string; Icon: LucideIcon }[] = [
  // Já existentes
  { name: 'Home', Icon: Home },
  { name: 'Film', Icon: Film },
  { name: 'Clapperboard', Icon: Clapperboard },
  { name: 'Camera', Icon: Camera },
  { name: 'DollarSign', Icon: DollarSign },
  { name: 'Wallet', Icon: Wallet },
  { name: 'CreditCard', Icon: CreditCard },
  { name: 'Banknote', Icon: Banknote },
  { name: 'FileText', Icon: FileText },
  { name: 'FileCheck', Icon: FileCheck },
  { name: 'ScrollText', Icon: ScrollText },
  { name: 'ClipboardList', Icon: ClipboardList },
  { name: 'StickyNote', Icon: StickyNote },
  { name: 'PenLine', Icon: PenLine },
  { name: 'Image', Icon: Image },
  { name: 'LayoutGrid', Icon: LayoutGrid },
  { name: 'Calendar', Icon: Calendar },
  { name: 'CalendarDays', Icon: CalendarDays },
  { name: 'ListOrdered', Icon: ListOrdered },
  { name: 'Users', Icon: Users },
  { name: 'User', Icon: User },
  { name: 'BarChart3', Icon: BarChart3 },
  { name: 'PieChart', Icon: PieChart },
  { name: 'Target', Icon: Target },
  { name: 'Settings', Icon: Settings },
  { name: 'FolderOpen', Icon: FolderOpen },
  { name: 'Receipt', Icon: Receipt },
  { name: 'Truck', Icon: Truck },
  { name: 'UtensilsCrossed', Icon: UtensilsCrossed },
  { name: 'Shirt', Icon: Shirt },
  { name: 'Paintbrush', Icon: Paintbrush },
  { name: 'Mic', Icon: Mic },
  { name: 'Headphones', Icon: Headphones },
  { name: 'Wrench', Icon: Wrench },
  { name: 'Box', Icon: Box },
  { name: 'Car', Icon: Car },
  { name: 'Coffee', Icon: Coffee },
  { name: 'Building2', Icon: Building2 },
  { name: 'Mail', Icon: Mail },
  { name: 'Phone', Icon: Phone },
  { name: 'MapPin', Icon: MapPin },
  { name: 'AlertCircle', Icon: AlertCircle },
  { name: 'CheckCircle', Icon: CheckCircle },
  { name: 'Clock', Icon: Clock },
  { name: 'Info', Icon: Info },
  { name: 'ChevronRight', Icon: ChevronRight },
  { name: 'Search', Icon: Search },
  { name: 'Plus', Icon: Plus },
  { name: 'Trash2', Icon: Trash2 },
  { name: 'Edit', Icon: Edit },
  { name: 'Copy', Icon: Copy },
  { name: 'Save', Icon: Save },
  { name: 'LogOut', Icon: LogOut },
  { name: 'Menu', Icon: Menu },
  { name: 'X', Icon: X },
  // Vídeo e multimídia
  { name: 'Video', Icon: Video },
  { name: 'VideoOff', Icon: VideoOff },
  { name: 'Play', Icon: Play },
  { name: 'Pause', Icon: Pause },
  { name: 'SkipForward', Icon: SkipForward },
  { name: 'SkipBack', Icon: SkipBack },
  { name: 'Square', Icon: Square },
  { name: 'Tv', Icon: Tv },
  { name: 'Monitor', Icon: Monitor },
  { name: 'MonitorPlay', Icon: MonitorPlay },
  { name: 'Images', Icon: Images },
  { name: 'ImagePlus', Icon: ImagePlus },
  // Escrita
  { name: 'Pencil', Icon: Pencil },
  { name: 'Highlighter', Icon: Highlighter },
  { name: 'Pen', Icon: Pen },
  { name: 'FilePenLine', Icon: FilePenLine },
  // Documentos
  { name: 'File', Icon: File },
  { name: 'FilePlus', Icon: FilePlus },
  { name: 'FileMinus', Icon: FileMinus },
  { name: 'Folder', Icon: Folder },
  { name: 'FolderPlus', Icon: FolderPlus },
  { name: 'Archive', Icon: Archive },
  // Dinheiro e pagamentos
  { name: 'CircleDollarSign', Icon: CircleDollarSign },
  { name: 'BadgeDollarSign', Icon: BadgeDollarSign },
  // Navegação, abrir/fechar, copiar/colar, avançar/excluir
  { name: 'ChevronLeft', Icon: ChevronLeft },
  { name: 'ChevronDown', Icon: ChevronDown },
  { name: 'ChevronUp', Icon: ChevronUp },
  { name: 'ArrowRight', Icon: ArrowRight },
  { name: 'ArrowLeft', Icon: ArrowLeft },
  { name: 'PanelRightOpen', Icon: PanelRightOpen },
  { name: 'PanelLeftClose', Icon: PanelLeftClose },
  { name: 'DoorOpen', Icon: DoorOpen },
  { name: 'DoorClosed', Icon: DoorClosed },
  { name: 'ClipboardCopy', Icon: ClipboardCopy },
  { name: 'ClipboardPaste', Icon: ClipboardPaste },
  { name: 'Minus', Icon: Minus },
  // Contatos
  { name: 'MessageCircle', Icon: MessageCircle },
  { name: 'MessageSquare', Icon: MessageSquare },
  { name: 'ContactRound', Icon: ContactRound },
  { name: 'Send', Icon: Send },
  // Planilhas, cadernos, textos, folhas, anotações
  { name: 'Notebook', Icon: Notebook },
  { name: 'NotebookText', Icon: NotebookText },
  { name: 'NotebookTabs', Icon: NotebookTabs },
  { name: 'Sheet', Icon: Sheet },
  { name: 'BookOpen', Icon: BookOpen },
  { name: 'BookMarked', Icon: BookMarked },
  { name: 'FileStack', Icon: FileStack },
  { name: 'FileType', Icon: FileType },
]
